# Generated by Django 2.1.7 on 2019-05-20 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TelegramAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('file_id', models.TextField(unique=True)),
                ('mime_type', models.CharField(max_length=30)),
                ('file_size', models.IntegerField()),
                ('file_name', models.CharField(max_length=1000)),
                ('file_description', models.CharField(max_length=1025, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TelegramAdmin.User')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-download_count', '-created_at'],
            },
        ),
    ]
