# Generated by Django 2.1.7 on 2019-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='search_field',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(max_length=100),
        ),
    ]
